name: nightly build
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --before="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}    
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: get custom react music player
        run: git clone https://github.com/lovegaoshi/react-music-player.git Dependencies/react-jinke-music-player
        
      - name: build rjmp
        run: cd Dependencies/react-jinke-music-player && yarn && yarn build

      - name: Install dependencies
        run: yarn
        
      - name: yarn build
        run: yarn build

      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ steps.date.outputs.date }}
          files: build.zip
