name: auto-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Tag
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Display Tag
        run: echo "${{ steps.get_tag.outputs.tag }}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: get custom react music player
        run: git clone https://github.com/lovegaoshi/react-music-player.git ../react-music-player

      - name: build rjmp
        run: cd ../react-music-player && yarn && yarn build

      - name: Install dependencies
        run: yarn; git submodule update --init --recursive

      - name: Install dependencies
        run: yarn

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Get Recent Commit Tag
        id: get_commit_tag
        run: |
          COMMIT_TAG=$(git describe --tags --abbrev=0)
          echo "COMMIT_TAG=${COMMIT_TAG}" >> $GITHUB_ENV

      - name: Display Commit Tag
        run: |
          echo "Commit Tag: $COMMIT_TAG"

      - name: yarn build
        run: yarn build

      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Unpacked ${{env.COMMIT_TAG}}'
          files: build.zip
          generate_release_notes: true

      - name: Edge Publish
        uses: wdzeng/edge-addon@v1
        with:
          product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          zip-path: build.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
